#!/system/xbin/bash

export PATH=/system/xbin:/system/bin

busybox mount /boot -o remount,rw

case "$1" in
    recovery)
        CMD="ClockworkMod"
        if [ -r /data/local/moboot.default.recovery ];
        then
            CMD=`cat /data/local/moboot.default.recovery`
        fi
        ;;
    altos)
        CMD="webOS"
        ;;
    *)
        CMD="$1"
        ;;
esac

# possibly we need to check if the target exists, but
# currently moboot ignores invalid targets so we are good
echo -n $CMD >/boot/moboot.next
sync
busybox umount /boot
